### ISSUE TITLE
Any licensing required for usage of this notify.js solution ?

### ISSUE THREAD

**Issue by ssaurabhz** [PaulNieuwelaar/notifyjs#1]
Hi Paul,
I was looking for something similar (for my project) what you have developed for showing notifications on CRM UI, so I want to check with you if there are any licensing steps required before I can start using your notify.js tool? 
If not, I can go-ahead and use it. Will need your input on this. Let me know please.

Thanks,
Saurabh

**Comment by PaulNieuwelaar** [comment]
Hi, there was a general use license which basically says you can use it in your projects for free, and tweak it if needed, just maintain the copyright notice at the top of the files, and link back to the github project where necessary, and don't go on to sell any part of the code claiming it as your own etc. Cheers, Paul
