### ISSUE TITLE
Can we use Dropdown instead of a button

### ISSUE THREAD

**Issue by tech7857** [PaulNieuwelaar/notifyjs#3]
Hi 

Is it possible to place dropdown in the notification in addition to buttons and links

**Comment by PaulNieuwelaar** [comment]
Hi, 

You can pass custom HTML to the notification, so in theory you could do something like add a &lt;select> tag with &lt;option>'s, and set a function to call onchange of the select etc.
 
Paul

**Comment by tech7857** [comment]
Hi Paul

Thanks for the quick reply. Will it be possible for you to provide a sample. It will be really helpful.

Thanks

**Comment by PaulNieuwelaar** [comment]
Hi, Here's a sample of how to show a dropdown list inside the notification. Any custom HTML can be passed into the notification message. You can then access custom elements from the notification using "parent.document..." as shown below:

```
Notify.add("Please select the priority: <select id='priorityList'><option>High</option><option selected='selected'>Normal</option><option>Low</option></select> ", "INFO", "priority", [{text:"OK", callback:function(){Notify.remove("priority");alert(parent.document.getElementById("priorityList").value);}}, {text:"Cancel", type:"link", callback:function(){Notify.remove("priority");}}]);
```

![notify](https://user-images.githubusercontent.com/14048382/33097148-17567f8c-cf6e-11e7-8279-da2c55f0e892.PNG)

I'll be adding a section to the documentation explaining how this can be done in more detail.

Hope that helps
Paul
