### ISSUE TITLE
Notifications can not be closed

### ISSUE THREAD

**Issue by jarlucmat** [PaulNieuwelaar/notifyjs#4]
I experienced an issue with the Notifications on firefox and chrome (didn't check edge). The Notifications can not be closed whether by the built-in duration parameter nor by the close button. This happens sometimes depending on how fast the page loads and can be mitigated by adding a timeout function before actually calling Notify.add(...). 
When this error happens i also tried calling manually jQuery to close the specific Notification but this did not work either.
Tested this on a dynamics test instance, Version should be 9.2.....

**Comment by PaulNieuwelaar** [comment]
Hi, I tested this and it seems to be working OK for me. Are you calling it in the form onload event? Are you loading the Notify.js web resource anywhere else, i.e. from a ribbon button or other web resource loaded into the page? Any other info about how you're using it or how to reproduce the issue would be appreciated. Cheers, Paul

**Comment by jarlucmat** [comment]
Hi, thx for the fast answer. Yes, you are right, i use a javascript with a form onload event which calls the Notify.add() function. The notifiy.js library is added to the form libraries before my javascript. Maybe i am doing something wrong here.? There is no other loading of the Notify.js web resource anywhere else.

I believe that this error has something to do with jquery because i can still address and hide the elements when using queryselector. This error is also independent of the form, because i tried it in accounts and contacts.

**Comment by jarlucmat** [comment]
I just created a new dynamic instance and was not able to reproduce the error. The major difference between the new and old instance is that i enabled all scenarios (sales, project service...) during setup of the old instance.

**Comment by PaulNieuwelaar** [comment]
Hi, do you have a different version of jquery being loaded onto the form somewhere?

**Comment by jarlucmat** [comment]
Well... i don't have the test instance anymore (trial ended) but in case the error appears again, how do i check this?

**Comment by PaulNieuwelaar** [comment]
Hi, you can check it from the form properties, and check the js libraries being loaded into the form. One of those add-ons might have been loading an old jQuery version onto the form which doesn't have some of the features required.
