### ISSUE TITLE
HI, did this Notify: CRM header element: 'undefined' does not exist. solved? i have the same problem with UUI v9.1 ? how to solve it ? i install notify version 2.0 but it didn't help.

### ISSUE THREAD

**Issue by Mehran16007** [PaulNieuwelaar/notifyjs#8]
HI, did this problem solved? i have the same problem with UUI v9.1 ? how to solve it ? i install notify version 2.0 but it didn't help.

**Comment by PaulNieuwelaar** [comment]
Hi, The v2 solution should definitely still work in the unified interface (just tested both forms and views). The error you're referencing sounds like it's from the v1.1 solution. Did you have your own web resource prefix on the v1.1 files? If so you may need to manually update these.

**Comment by Mehran16007** [comment]
yes Paul that was my bad the version 2.0 worked for me after login again in crm.
